### ISSUE TITLE
[Feature request] Publish binaries, brew packages, deb and rpm packages :-)

### ISSUE THREAD

**Issue by kishaningithub** [maaslalani/gambit#1]
This will make is cool chess game highly accessible for everyone :-) 

I use goreleaser for all my go projects to acheive the same

https://goreleaser.com/

Example repo (my repo): https://github.com/kishaningithub/shopify-csv-download/releases

Let me know if you are fine with this,  i can work on a PR for the same :-)

**Comment by maaslalani** [comment]
Hey! Thanks so much for creating this issue, I normally like to leave publishing binaries automatically if a library of mine gets reasonably popular enough like https://github.com/maaslalani/slides where I do automatic binary publishing. I don't think it makes sense currently to do this for `gambit`, hopefully one day it will 😄
